import React, { useState } from 'react';
import { GlassCard } from './ui/GlassCard';
import { GoogleGenAI } from "@google/genai";

export const GeminiAssistant: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [response, setResponse] = useState('');
  const [loading, setLoading] = useState(false);

  // We are using a mock simulation here because the user's HTML prompt implied a script but no API Key was provided
  // in the env variables for this generation session. 
  // However, I will include the structure for real integration if KEY is present.
  
  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setResponse('');

    try {
       // Check if API KEY is available in environment (In a real scenario)
       const apiKey = process.env.API_KEY; 
       
       if (apiKey) {
         const ai = new GoogleGenAI({ apiKey });
         const aiResponse = await ai.models.generateContent({
            model: 'gemini-2.5-flash-preview-09-2025',
            contents: `As an expert event consultant for 995 EVENTS, provide a creative, high-impact concept for: ${prompt}. Keep it concise (under 150 words) and list 3 key innovative features.`,
         });
         setResponse(aiResponse.text || "No response from AI.");
       } else {
         // Simulation fallback if no key (for demo purpose as requested by prompt context "Generate complete code")
         await new Promise(resolve => setTimeout(resolve, 2000));
         setResponse(`🎯 **AI Concept for "${prompt}":**\n\n**Theme:** "Future Forward Experience"\n\n**Key Features:**\n1. **Holographic Keynote:** Live 3D projection of speakers.\n2. **AI Networking Match:** Smart badges that glow when near relevant contacts.\n3. **Real-time Sentiment Wall:** Visualizing attendee excitement using data art.\n\n*Generated by 995 EVENTS AI Engine*`);
       }
    } catch (error) {
      console.error(error);
      setResponse("Consultation systems are currently busy. Please contact our team directly.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <section id="ai-consultant" className="py-24 relative bg-deep-blue/20">
      <div className="container mx-auto px-6 max-w-4xl relative z-10">
        <GlassCard className="p-8 md:p-12 border-neon-purple/50">
          <div className="text-center mb-8">
            <span className="inline-block py-1 px-3 rounded-full bg-neon-purple/20 text-neon-purple text-xs font-bold tracking-widest mb-4 border border-neon-purple/50">
              POWERED BY GEMINI 2.5
            </span>
            <h2 className="text-3xl font-heading font-bold text-white mb-4 neon-shadow-text-magenta">
              AI Event Consultant
            </h2>
            <p className="text-gray-300 font-body">
              Need inspiration? Tell our AI engine your event goal, and get an instant creative concept.
            </p>
          </div>

          <div className="space-y-6">
            <div className="relative">
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="E.g., A futuristic product launch for a new energy drink aiming for Gen Z..."
                className="w-full bg-bg-dark/50 border border-white/20 rounded-xl p-4 text-white placeholder-gray-500 focus:outline-none focus:border-neon-purple focus:ring-1 focus:ring-neon-purple transition-all min-h-[120px]"
              />
            </div>

            <div className="text-center">
              <button 
                onClick={handleGenerate}
                disabled={loading || !prompt}
                className={`magic-button magenta px-8 py-3 rounded-full font-bold tracking-wider ${loading ? 'opacity-50 cursor-not-allowed' : ''}`}
              >
                {loading ? 'ANALYZING...' : 'GENERATE CONCEPT'}
              </button>
            </div>

            {response && (
              <div className="mt-8 p-6 bg-white/5 rounded-xl border border-white/10 animate-fade-in-up">
                <div className="prose prose-invert max-w-none">
                  <p className="whitespace-pre-wrap font-body text-gray-200 leading-relaxed">
                    {response}
                  </p>
                </div>
              </div>
            )}
          </div>
        </GlassCard>
      </div>
    </section>
  );
};
